// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf9wuEg2IYArzCzf-VKmIvLXOr20O7UOk',
    appId: '1:722321231787:web:2f516f603216a580794cee',
    messagingSenderId: '722321231787',
    projectId: 'audios-453ef',
    authDomain: 'audios-453ef.firebaseapp.com',
    databaseURL: 'https://audios-453ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'audios-453ef.appspot.com',
    measurementId: 'G-2MZMW2J8QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUz0qEHRmsF41Irq8L63TF-8F2o_f_yyE',
    appId: '1:722321231787:android:05988b991711b763794cee',
    messagingSenderId: '722321231787',
    projectId: 'audios-453ef',
    databaseURL: 'https://audios-453ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'audios-453ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCziLW9uIrE0YLao40eowEadr6iYRBqNJM',
    appId: '1:722321231787:ios:9d3343525835da18794cee',
    messagingSenderId: '722321231787',
    projectId: 'audios-453ef',
    databaseURL: 'https://audios-453ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'audios-453ef.appspot.com',
    iosClientId: '722321231787-v2fgiv9i7sc0nu5q7ugjknptr7kgaa8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.babytalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCziLW9uIrE0YLao40eowEadr6iYRBqNJM',
    appId: '1:722321231787:ios:9d3343525835da18794cee',
    messagingSenderId: '722321231787',
    projectId: 'audios-453ef',
    databaseURL: 'https://audios-453ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'audios-453ef.appspot.com',
    iosClientId: '722321231787-v2fgiv9i7sc0nu5q7ugjknptr7kgaa8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.babytalk',
  );
}
